
-- Create the appointments table
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    appointment_date DATE NOT NULL,
    time_slot TEXT,
    floorplan TEXT,
    purpose TEXT,
    services TEXT[],
    message TEXT
);

-- Enable RLS for the appointments table
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- Create policies for the appointments table
-- Allow public access to insert new appointments
CREATE POLICY "Allow public insert" ON appointments FOR INSERT WITH CHECK (true);

-- Allow admin users to read all appointments
CREATE POLICY "Allow admin read access" ON appointments FOR SELECT USING (true);
