
-- Drop tables if they exist to start fresh
DROP TABLE IF EXISTS "sections";
DROP TABLE IF EXISTS "pages";
DROP TABLE IF EXISTS "stories";

-- Create the pages table
CREATE TABLE "pages" (
  "id" bigserial PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "title" text NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "meta_title" text,
  "meta_description" text
);

-- Create the sections table
CREATE TABLE "sections" (
  "id" bigserial PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "page_id" bigint NOT NULL REFERENCES "pages" ("id") ON DELETE CASCADE,
  "title" text NOT NULL,
  "type" text NOT NULL,
  "content" jsonb,
  "content_structure" jsonb,
  "visible" boolean NOT NULL DEFAULT true,
  "order" integer NOT NULL DEFAULT 0
);

-- Create the stories table for customer stories
CREATE TABLE "stories" (
  "id" bigserial PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  "slug" text NOT NULL UNIQUE,
  "title" text NOT NULL,
  "image" text,
  "dataAiHint" text,
  "category" text,
  "author" text,
  "authorAvatar" text,
  "date" text,
  "excerpt" text,
  "clientImage" text,
  "location" text,
  "project" text,
  "size" text,
  "quote" text,
  "content" text,
  "gallery" jsonb
);

-- Seed data for pages
INSERT INTO "pages" ("title", "slug", "meta_title", "meta_description") VALUES
('Home', 'home', 'Shriram Interio | Pune''s Premier Interior Designers', 'Discover bespoke interior designs for modular kitchens, wardrobes, and full homes in Pune with Shriram Interio. Your dream space awaits.'),
('About Us', 'about', 'About Shriram Interio | Our Story & Team', 'Learn about Shriram Interio''s journey, our mission, vision, and the expert team dedicated to creating beautiful and functional living spaces.'),
('Customer Stories', 'customer-stories', 'Customer Success Stories | Shriram Interio', 'Read inspiring stories from our happy clients. See how we transformed their houses into dream homes with our expert interior design services.'),
('Clients', 'clients', 'Our Clients | Testimonials & Reviews', 'Hear directly from our clients. Read testimonials and watch video reviews from homeowners who trusted Shriram Interio with their design projects.'),
('Services', 'services', 'Our Interior Design Services | Shriram Interio', 'Explore our comprehensive interior design services, including modular kitchens, wardrobes, full home interiors, and more.'),
('Portfolio', 'portfolio', 'Interior Design Portfolio | Shriram Interio', 'Browse our portfolio of completed projects. See the quality and creativity of our work in kitchens, living areas, and bedrooms.'),
('How It Works', 'how-it-works', 'Our Design Process | From Concept to Completion', 'Understand our seamless 6-step design process that takes your vision from initial consultation to final installation with transparency and expertise.'),
('Contact', 'contact', 'Contact Shriram Interio | Get In Touch', 'Contact us for a free consultation. Find our address, phone number, and email to start your interior design journey.'),
('Products', 'products', 'Our Products | Kitchens, Wardrobes & More', 'Discover our range of high-quality interior design products, including modular kitchens, custom wardrobes, and space-saving furniture.');


-- Seed data for sections
DO $$
DECLARE
    home_page_id bigint;
    about_page_id bigint;
    stories_page_id bigint;
    clients_page_id bigint;
    services_page_id bigint;
    portfolio_page_id bigint;
    howitworks_page_id bigint;
    contact_page_id bigint;
    products_page_id bigint;
BEGIN
    -- Get page IDs
    SELECT id INTO home_page_id FROM pages WHERE slug = 'home';
    SELECT id INTO about_page_id FROM pages WHERE slug = 'about';
    SELECT id INTO stories_page_id FROM pages WHERE slug = 'customer-stories';
    SELECT id INTO clients_page_id FROM pages WHERE slug = 'clients';
    SELECT id INTO services_page_id FROM pages WHERE slug = 'services';
    SELECT id INTO portfolio_page_id FROM pages WHERE slug = 'portfolio';
    SELECT id INTO howitworks_page_id FROM pages WHERE slug = 'how-it-works';
    SELECT id INTO contact_page_id FROM pages WHERE slug = 'contact';
    SELECT id INTO products_page_id FROM pages WHERE slug = 'products';

    -- Home Page Sections
    INSERT INTO "sections" ("page_id", "title", "type", "content", "content_structure", "order") VALUES
    (home_page_id, 'Hero Section', 'hero', '{"title": "Transforming Houses into Dream Homes", "subtitle": "Pune''s leading interior design company for modular kitchens, wardrobes, and full home interiors.", "buttonText": "Explore Our Services", "videoUrl": "https://www.shriraminterio.com/wp-content/uploads/2024/05/10000000_1132049694776109_532975988143399435_n.mp4", "slides": [{"image": "https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1920&q=80"}, {"image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1920&q=80"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "textarea", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}, "videoUrl": {"type": "text", "label": "Background Video URL"}, "slides": {"type": "repeater", "label": "Image Slides", "fields": {"image": {"type": "image", "label": "Image"}}}}', 0),
    (home_page_id, 'Welcome', 'welcome', '{"paragraph1": "We specialize in crafting beautiful and functional modular kitchens and wardrobes. Our expert team combines creativity and precision to deliver personalized solutions that elevate your living space.", "paragraph2": "From initial design to final installation, we ensure a seamless and satisfying experience, turning your vision into reality.", "image": "/Designer.png"}', '{"paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "image": {"type": "image", "label": "Image"}}', 1),
    (home_page_id, 'About Company', 'about_company', '{"title": "We Are Shriram Interio", "text": "is a place where design meets inspiration and innovation. Founded on the belief that exceptional design transforms lives, we are a team of passionate creatives dedicated to curating spaces that resonate with your soul."}', '{"title": {"type": "text", "label": "Title"}, "text": {"type": "textarea", "label": "Text"}}', 2),
    (home_page_id, 'Why Us', 'why_us', '{"title": "Why Shriram Interio?", "subtitle": "Your one-stop destination for complete home interiors.", "items": [{"title": "Expert Design Team", "description": "Talented designers who bring your vision to life."}, {"title": "Variety of Design Choices", "description": "A wide range of styles, materials, and finishes to suit your taste."}, {"title": "Affordable Design Fees", "description": "High-quality design that fits your budget without compromising on excellence."}, {"title": "On-Time Project Delivery", "description": "We respect your time and are committed to delivering projects as scheduled."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}}}}', 3),
    (home_page_id, 'Work Gallery', 'work_gallery', '{"title": "Our Work Gallery", "subtitle": "Explore our portfolio of stunning interior designs.", "items": [{"title": "L-Shape Modular Kitchen", "image": "/L-shape-kitchen.png", "hint": "modular kitchen"}, {"title": "U-Shape Modular Kitchen", "image": "/U-shape-kitchen.png", "hint": "u-shaped kitchen"}, {"title": "Island Modular Kitchen", "image": "/Island-Kitchen.png", "hint": "island kitchen"}, {"title": "Sliding Wardrobe", "image": "/SlidingWardrobe.jpg", "hint": "sliding wardrobe"}, {"title": "Hinged Wardrobe", "image": "/HingedWardrobe.jpg", "hint": "hinged wardrobe"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Gallery Items", "fields": {"title": {"type": "text", "label": "Title"}, "image": {"type": "image", "label": "Image"}, "hint": {"type": "text", "label": "AI Hint"}}}}', 4),
    (home_page_id, 'Design At Your Comfort', 'comfort_design', '{"title": "Design At Your Comfort", "subtitle": "Our innovative approach to interior design brings the showroom to you.", "items": [{"title": "Live 3D Designs", "description": "Experience your future home with live 3D visualization sessions."}, {"title": "Contactless Experience", "description": "From discussion to design, enjoy a completely remote and safe process."}, {"title": "Instant Pricing", "description": "Get transparent, upfront pricing for your project with no hidden costs."}, {"title": "Expertise & Passion", "description": "Our team''s dedication and expertise ensure your dream home becomes a reality."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}}}}', 5),
    (home_page_id, 'What We Do', 'what_we_do', '{"title": "What We Do?", "subtitle": "Discover our range of best-selling and trending interior solutions.", "trendingItems": [{"name": "Two-toned Kitchen Cabinets", "image": "/kitchen.jpg", "hint": "kitchen cabinets"}, {"name": "Walk-in Wardrobes", "image": "/w1.jpg", "hint": "walk-in wardrobe"}, {"name": "Minimalist TV Units", "image": "/b2.jpg", "hint": "tv unit"}, {"name": "Compact Study Nooks", "image": "/b1.jpg", "hint": "study nook"}], "bestSellingKitchens": [{"name": "Classic L-Shape", "image": "/L-shape-kitchen.png", "hint": "l-shaped kitchen"}, {"name": "Modern U-Shape", "image": "/U-shape-kitchen.png", "hint": "u-shaped kitchen"}, {"name": "Spacious Island", "image": "/Island-Kitchen.png", "hint": "island kitchen"}, {"name": "Efficient Parallel", "image": "/kitchen-4.png", "hint": "parallel kitchen"}], "bestSellingWardrobes": [{"name": "Sleek Sliding Door", "image": "/SlidingWardrobe.jpg", "hint": "sliding wardrobe"}, {"name": "Elegant Hinged Door", "image": "/HingedWardrobe.jpg", "hint": "hinged wardrobe"}, {"name": "Luxurious Walk-in", "image": "/w1.jpg", "hint": "walk-in wardrobe"}, {"name": "Compact & Functional", "image": "/w2.jpg", "hint": "small wardrobe"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "trendingItems": {"type": "repeater", "label": "Trending Items"}, "bestSellingKitchens": {"type": "repeater", "label": "Best Selling Kitchens"}, "bestSellingWardrobes": {"type": "repeater", "label": "Best Selling Wardrobes"}}', 6),
    (home_page_id, 'Testimonials', 'testimonials', '{"title": "Happy Customers", "subtitle": "Don''t just take our word for it. Hear from our delighted clients.", "buttonText": "Read All Customer Stories", "items": [{"name": "Rohan & Priya", "review": "Shriram Interio turned our small apartment into a spacious and beautiful home. Their attention to detail is commendable!", "image": "https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwbWFufGVufDB8fHx8MTc1NTYyNDQyMnww&ixlib=rb-4.1.0&q=80&w=1080"}, {"name": "Anita Desai", "review": "The modular kitchen they designed is not only stunning but also incredibly functional. Cooking is a joy now!", "image": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwd29tYW58ZW58MHx8fHwxNzU1NjI0NDQyfDA&ixlib=rb-4.1.0&q=80&w=1080"}, {"name": "The Verma Family", "review": "The full home interior was handled professionally from start to finish. Highly recommended for their quality and service.", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}, "items": {"type": "repeater", "label": "Testimonials"}}', 7),
    (home_page_id, 'FAQ', 'faq', '{"title": "Frequently Asked Questions", "subtitle": "Have questions? We have answers.", "items": [{"question": "What is the typical timeline for a project?", "answer": "A typical project timeline ranges from 4 to 8 weeks, depending on the scope and complexity. We provide a detailed schedule at the beginning of each project."}, {"question": "Do you offer a warranty on your work?", "answer": "Yes, we offer a one-year warranty on all our workmanship and materials, ensuring peace of mind for our clients."}, {"question": "Can I see my design in 3D before execution?", "answer": "Absolutely! We provide detailed 3D visualizations to help you see exactly how your space will look, allowing for changes before we begin manufacturing."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "FAQ Items"}}', 8),
    (home_page_id, 'Partners', 'partners', '{"title": "Our Trusted Partners", "subtitle": "BRANDS WE ARE ASSOCIATED WITH", "items": [{"name": "Hettich", "logoSrc": "/p1.png"}, {"name": "Hafele", "logoSrc": "/p2.png"}, {"name": "Faber", "logoSrc": "/p3.jpg"}, {"name": "Elica", "logoSrc": "/p4.png"}, {"name": "Greenply", "logoSrc": "/p5.jpg"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Partners"}}', 9);
    
    -- About Page Sections
    INSERT INTO "sections" ("page_id", "title", "type", "content", "content_structure", "order") VALUES
    (about_page_id, 'Hero', 'hero', '{"title": "About Shriram Interio", "subtitle": "Designing spaces that tell your story", "backgroundImage": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxpbnRlcmlvciUyMGRlc2lnbnxlbnwwfHx8fDE3NTU2MjM5NjR8MA&ixlib=rb-4.1.0&q=80&w=1080"}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "backgroundImage": {"type": "image", "label": "Background Image"}}', 0),
    (about_page_id, 'Our Story', 'story', '{"heading": "Our Story", "subheading": "Crafting beautiful spaces since 2016.", "paragraph1": "SHRIRAM INTERIO is a place where design meets inspiration and innovation. Founded on the belief that exceptional design transforms lives, we are a team of passionate creatives dedicated to curating spaces that resonate with your soul.", "paragraph2": "Since our establishment in 2016, our journey began with a shared vision: to redefine interior design by infusing creativity, functionality, and a personalized touch into every project. Over the years, we''ve evolved, but our commitment to excellence remains unwavering.", "paragraph3": "Our portfolio is a testament to our versatility, showcasing a diverse range of projects from cozy residential interiors to dynamic commercial spaces. Each project is a unique story, a collaboration between our expertise and our clients'' aspirations.", "paragraph4": "At SHRIRAM INTERIO, we don''t just design spaces; we craft experiences. We invite you to explore our world of design and discover how we can bring your vision to life.", "image": "https://images.unsplash.com/photo-1572021335469-31706a17aaef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0ZWFtJTIwY29sbGFib3JhdGlvbnxlbnwwfHx8fDE3NTU2MjQyOTl8MA&ixlib=rb-4.1.0&q=80&w=1080"}', '{"heading": {"type": "text", "label": "Heading"}, "subheading": {"type": "text", "label": "Subheading"}, "paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "paragraph3": {"type": "textarea", "label": "Paragraph 3"}, "paragraph4": {"type": "textarea", "label": "Paragraph 4"}, "image": {"type": "image", "label": "Image"}}', 1),
    (about_page_id, 'Our Journey', 'journey', '{"heading": "Our Journey", "paragraph1": "Our journey is a narrative of passion, perseverance, and a relentless pursuit of perfection. From humble beginnings, we have grown into a reputable design firm, known for our innovative solutions and client-centric approach. We believe in the power of collaboration, working closely with our clients to understand their needs and translate their dreams into tangible, beautiful realities.", "paragraph2": "We have navigated the evolving landscape of design, embracing new technologies and trends while staying true to our core principles of quality and craftsmanship. Our team is our greatest asset, a collective of creative minds who bring a wealth of experience and a fresh perspective to every project.", "paragraph3": "Every space we design is a chapter in our story, a reflection of our commitment to creating environments that are not only aesthetically pleasing but also enhance the quality of life. We are proud of the relationships we have built and the trust we have earned.", "paragraph4": "As we look to the future, we are excited to continue our journey, pushing the boundaries of design and creating spaces that inspire and endure.", "image": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxkZXNpZ24lMjBtb29kJTIwYm9hcmR8ZW58MHx8fHwxNzU1NjI0MzA3fDA&ixlib=rb-4.1.0&q=80&w=1080"}', '{"heading": {"type": "text", "label": "Heading"}, "paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "paragraph3": {"type": "textarea", "label": "Paragraph 3"}, "paragraph4": {"type": "textarea", "label": "Paragraph 4"}, "image": {"type": "image", "label": "Image"}}', 2),
    (about_page_id, 'Our Values', 'values', '{"title": "Our Core Values", "subtitle": "The principles that guide our work and define our character.", "items": [{"title": "Expert Design Team", "description": "Talented designers who bring your vision to life."}, {"title": "Variety of Design Choices", "description": "A wide range of styles, materials, and finishes to suit your taste."}, {"title": "Affordable Design Fees", "description": "High-quality design that fits your budget without compromising on excellence."}, {"title": "On-Time Project Delivery", "description": "We respect your time and are committed to delivering projects as scheduled."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Values"}}', 3),
    (about_page_id, 'Mission and Vision', 'mission_vision', '{"visionTitle": "Our Vision", "visionText": "To be the leading interior design firm in Pune, recognized for our creativity, innovation, and unwavering commitment to client satisfaction.", "missionTitle": "Our Mission", "missionText": "To create timeless, functional, and beautiful spaces that enhance the lives of our clients, through a collaborative and transparent design process."}', '{"visionTitle": {"type": "text", "label": "Vision Title"}, "visionText": {"type": "textarea", "label": "Vision Text"}, "missionTitle": {"type": "text", "label": "Mission Title"}, "missionText": {"type": "textarea", "label": "Mission Text"}}', 4),
    (about_page_id, 'Meet the Team', 'team', '{"title": "Meet Our Team", "subtitle": "The creative minds behind our successful designs.", "members": [{"name": "Mr. Shriram", "role": "Founder & Lead Designer", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "bio": "With over a decade of experience, Mr. Shriram leads our team with a passion for innovative design and a commitment to excellence."}, {"name": "Priya Sharma", "role": "Project Manager", "image": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "bio": "Priya ensures every project runs smoothly, from initial concept to final handover, guaranteeing client satisfaction."}, {"name": "Amit Kumar", "role": "Senior Interior Designer", "image": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "bio": "Amit specializes in creating functional and aesthetically pleasing spaces, with a keen eye for detail and a love for modern design."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "members": {"type": "repeater", "label": "Team Members"}}', 5);
    
    -- Customer Stories Page Sections
    INSERT INTO "sections" ("page_id", "title", "type", "content", "content_structure", "order") VALUES
    (stories_page_id, 'Header', 'header', '{"title": "Customer Stories", "subtitle": "Real stories from real homeowners. See how we have transformed their spaces and lives."}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "textarea", "label": "Subtitle"}}', 0),
    (stories_page_id, 'Featured Story', 'featured_story', '{"buttonText": "Read Full Story"}', '{"buttonText": {"type": "text", "label": "Button Text"}}', 1),
    (stories_page_id, 'More Stories', 'more_stories', '{"title": "More Inspiring Stories"}', '{"title": {"type": "text", "label": "Title"}}', 2),
    (stories_page_id, 'Work Gallery', 'work_gallery', '{"title": "Our Work Gallery", "subtitle": "Explore our portfolio of stunning interior designs.", "items": [{"title": "L-Shape Modular Kitchen", "image": "/L-shape-kitchen.png", "hint": "modular kitchen"}, {"title": "U-Shape Modular Kitchen", "image": "/U-shape-kitchen.png", "hint": "u-shaped kitchen"}, {"title": "Island Modular Kitchen", "image": "/Island-Kitchen.png", "hint": "island kitchen"}, {"title": "Sliding Wardrobe", "image": "/SlidingWardrobe.jpg", "hint": "sliding wardrobe"}, {"title": "Hinged Wardrobe", "image": "/HingedWardrobe.jpg", "hint": "hinged wardrobe"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Gallery Items"}}', 3),
    (stories_page_id, 'Partners', 'partners', '{"title": "Our Trusted Partners", "subtitle": "BRANDS WE ARE ASSOCIATED WITH", "items": [{"name": "Hettich", "logoSrc": "/p1.png"}, {"name": "Hafele", "logoSrc": "/p2.png"}, {"name": "Faber", "logoSrc": "/p3.jpg"}, {"name": "Elica", "logoSrc": "/p4.png"}, {"name": "Greenply", "logoSrc": "/p5.jpg"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Partners"}}', 4),
    (stories_page_id, 'FAQ', 'faq', '{"title": "Frequently Asked Questions", "subtitle": "Have questions? We have answers.", "items": [{"question": "What is the typical timeline for a project?", "answer": "A typical project timeline ranges from 4 to 8 weeks, depending on the scope and complexity. We provide a detailed schedule at the beginning of each project."}, {"question": "Do you offer a warranty on your work?", "answer": "Yes, we offer a one-year warranty on all our workmanship and materials, ensuring peace of mind for our clients."}, {"question": "Can I see my design in 3D before execution?", "answer": "Absolutely! We provide detailed 3D visualizations to help you see exactly how your space will look, allowing for changes before we begin manufacturing."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "FAQ Items"}}', 5);

    -- Clients Page Sections
    INSERT INTO "sections" ("page_id", "title", "type", "content", "content_structure", "order") VALUES
    (clients_page_id, 'Featured Testimonial', 'featured_testimonial', '{"image": "https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwbWFufGVufDB8fHx8MTc1NTYyNDQyMnww&ixlib=rb-4.1.0&q=80&w=1080", "location": "Pune", "project": "Full Home Interior", "size": "3 BHK", "quote": "The team at Shriram Interio exceeded all our expectations. The design was flawless, and the execution was even better.", "name": "Rohan Sharma", "review": "From the initial consultation to the final handover, the process was seamless. The team was professional, attentive, and incredibly skilled. They transformed our house into a home we truly love. We couldn''t be happier with the result and would recommend Shriram Interio to anyone looking for top-quality interior design."}', '{"image": {"type": "image"}, "location": {"type": "text"}, "project": {"type": "text"}, "size": {"type": "text"}, "quote": {"type": "textarea"}, "name": {"type": "text"}, "review": {"type": "textarea"}}', 0),
    (clients_page_id, 'Video Testimonials', 'video_testimonials', '{"title": "What Our Clients Say", "subtitle": "Watch our clients share their experiences with Shriram Interio.", "videos": [{"videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "imageSrc": "https://images.unsplash.com/photo-1521119989659-a83eee488004?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "name": "Priya & Sameer", "location": "Koregaon Park, Pune", "review": "Our kitchen is the heart of our home, and Shriram made it perfect.", "dataAiHint": "happy couple"}, {"videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "imageSrc": "https://images.unsplash.com/photo-1580489944761-15a19d654956?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "name": "Anjali Mehta", "location": "Baner, Pune", "review": "The wardrobe design maximized my space beautifully. I''m so happy!", "dataAiHint": "smiling woman"}, {"videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "imageSrc": "https://images.unsplash.com/photo-1599566150163-29194dcaad36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "name": "Vikram Singh", "location": "Hinjewadi, Pune", "review": "A truly professional and creative team. They delivered on time and on budget.", "dataAiHint": "man portrait"}]}', '{"title": {"type": "text"}, "subtitle": {"type": "text"}, "videos": {"type": "repeater"}}', 1),
    (clients_page_id, 'Text Testimonials', 'text_testimonials', '{"title": "More Happy Clients", "subtitle": "Read what our customers have to say about their experience.", "testimonials": [{"name": "Sunita Patil", "review": "Excellent service and brilliant design ideas. My living room has been completely transformed!", "image": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "avatar": "SP"}, {"name": "Rajesh Kumar", "review": "The team was very patient and incorporated all my ideas into the design. The final result is fantastic.", "image": "https://images.unsplash.com/photo-1552058544-f2b08422138a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxwZW9wbGUlMjBwb3J0cmFpdHxlbnwwfHx8fDE3NTU2MjQzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080", "avatar": "RK"}, {"name": "Meera Iyer", "review": "I love my new bedroom! It''s so serene and exactly what I wanted. Thank you, Shriram Interio!", "image": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwd29tYW58ZW58MHx8fHwxNzU1NjI0NDQyfDA&ixlib=rb-4.1.0&q=80&w=1080", "avatar": "MI"}]}', '{"title": {"type": "text"}, "subtitle": {"type": "text"}, "testimonials": {"type": "repeater"}}', 2);
    
    -- Services Page Sections
    INSERT INTO "sections" ("page_id", "title", "type", "content", "content_structure", "order") VALUES
    (services_page_id, 'Header', 'header', '{"title": "Our Services", "subtitle": "Comprehensive design solutions tailored to your lifestyle and needs."}', '{"title": {"type": "text"}, "subtitle": {"type": "textarea"}}', 0),
    (services_page_id, 'Our Services', 'our_services', '{"services": [{"title": "Modular Kitchen Design", "description": "Creating efficient, beautiful kitchens that are the heart of the home."}, {"title": "Wardrobe & Storage Solutions", "description": "Custom wardrobes and storage units that maximize space and style."}, {"title": "Bedroom Interiors", "description": "Designing peaceful and personal sanctuaries for rest and relaxation."}, {"title": "Living Area Design", "description": "Crafting welcoming and functional living spaces for family and friends."}, {"title": "Exterior Design Services", "description": "Enhancing your home''s curb appeal with thoughtful exterior design."}, {"title": "Full Home Interiors", "description": "A complete, end-to-end solution for a cohesive and harmonious home."}]}', '{"services": {"type": "repeater"}}', 1),
    (services_page_id, 'Detailed Services', 'detailed_services', '{"services": [{"href": "/products/kitchen", "imageSrc": "https://images.unsplash.com/photo-1559554704-0f74b35a8718?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxtb2R1bGFyJTIwa2l0Y2hlbnxlbnwwfHx8fDE3NTU3MTUzMDJ8MA&ixlib=rb-4.1.0&q=80&w=1080", "title": "Modular Kitchens", "dataAiHint": "modern kitchen"}, {"href": "/products/wardrobe", "imageSrc": "https://images.unsplash.com/photo-1614631446501-abcf76949eca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHx3YXJkcm9iZXN8ZW58MHx8fHwxNzU1NzE1MzkxfDA&ixlib=rb-4.1.0&q=80&w=1080", "title": "Custom Wardrobes", "dataAiHint": "modern wardrobe"}, {"href": "/products/living-room", "imageSrc": "/b2.jpg", "title": "Living Room Design", "dataAiHint": "living room"}]}', '{"services": {"type": "repeater"}}', 2);
    
    -- Portfolio Page Sections
    INSERT INTO "sections" ("page_id", "title", "type", "content", "content_structure", "order") VALUES
    (portfolio_page_id, 'Projects Gallery', 'projects_gallery', '{"projects": [{"id": 1, "title": "Modern Minimalist Kitchen", "category": "Kitchens", "imageSrc": "https://images.unsplash.com/photo-1559554704-0f74b35a8718?w=800", "dataAiHint": "minimalist kitchen"}, {"id": 2, "title": "Cozy Scandinavian Living Room", "category": "Living Areas", "imageSrc": "https://images.unsplash.com/photo-1615873968403-89e068629265?w=800", "dataAiHint": "scandinavian living room"}, {"id": 3, "title": "Elegant Walk-in Wardrobe", "category": "Wardrobes", "imageSrc": "https://images.unsplash.com/photo-1614631446501-abcf76949eca?w=800", "dataAiHint": "walk-in wardrobe"}, {"id": 4, "title": "Industrial Chic Home Office", "category": "Home Office", "imageSrc": "https://images.unsplash.com/photo-1554224324-49033481e25e?w=800", "dataAiHint": "industrial office"}, {"id": 5, "title": "Luxury Master Bedroom", "category": "Bedrooms", "imageSrc": "https://images.unsplash.com/photo-1617098900591-3f90928e8c54?w=800", "dataAiHint": "luxury bedroom"}, {"id": 6, "title": "Sleek U-Shaped Kitchen", "category": "Kitchens", "imageSrc": "https://images.unsplash.com/photo-1585261450736-67d578ff00b4?w=800", "dataAiHint": "u-shaped kitchen"}]}', '{"projects": {"type": "repeater"}}', 0),
    (portfolio_page_id, 'Partners', 'partners', '{"title": "Our Trusted Partners", "subtitle": "BRANDS WE ARE ASSOCIATED WITH", "items": [{"name": "Hettich", "logoSrc": "/p1.png"}, {"name": "Hafele", "logoSrc": "/p2.png"}, {"name": "Faber", "logoSrc": "/p3.jpg"}, {"name": "Elica", "logoSrc": "/p4.png"}, {"name": "Greenply", "logoSrc": "/p5.jpg"}]}', '{"title": {"type": "text"}, "subtitle": {"type": "text"}, "items": {"type": "repeater"}}', 1);

    -- Other page sections can be added here following the same pattern
    -- For now, the structure is in place for all pages.

END $$;

-- Seed data for stories
INSERT INTO "stories" ("slug", "title", "image", "dataAiHint", "category", "author", "authorAvatar", "date", "excerpt", "clientImage", "location", "project", "size", "quote", "content", "gallery") VALUES
('a-dream-kitchen-comes-to-life', 'A Dream Kitchen Comes to Life', 'https://images.unsplash.com/photo-1600566752355-709b0a11a783?w=800', 'modern kitchen', 'Kitchens', 'Priya Sharma', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100', 'May 15, 2024', 'See how we transformed a cramped, outdated kitchen into a spacious and modern culinary haven for the Sharma family.', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Koregaon Park, Pune', 'Modular Kitchen', '200 sq.ft.', 'It feels like a completely new home. We finally have the kitchen of our dreams!', '<p>The Sharma family came to us with a common problem: a kitchen that was too small, too dark, and too outdated for their modern lifestyle. They dreamed of an open, airy space where they could cook, entertain, and create memories.</p><p>Our design team started by knocking down a non-structural wall to open up the kitchen to the dining area. We chose a light color palette with white cabinets, quartz countertops, and a soft blue backsplash to maximize the feeling of space and light. Smart storage solutions, like pull-out pantries and deep drawers, were integrated to keep countertops clutter-free. The project was completed in just 6 weeks, on time and within budget.</p>', '[{"src": "https://images.unsplash.com/photo-1600566752355-709b0a11a783?w=800", "alt": "Wide shot of the kitchen", "dataAiHint": "u-shaped kitchen"}, {"src": "https://images.unsplash.com/photo-1600585152220-401e679a1f86?w=800", "alt": "Kitchen storage solutions", "dataAiHint": "kitchen storage"}, {"src": "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800", "alt": "Countertop detail", "dataAiHint": "quartz countertop"}]');
