
-- Create the quotes table
CREATE TABLE if not exists quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  name text,
  email text,
  phone text,
  floorplan text,
  purpose text,
  message text
);

-- RLS policies for quotes table
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;

-- Allow public read access to quotes
DROP POLICY IF EXISTS "Allow public read access" ON quotes;
CREATE POLICY "Allow public read access" ON quotes
  FOR SELECT USING (true);

-- Allow authenticated users to insert their own quotes
DROP POLICY IF EXISTS "Allow authenticated insert" ON quotes;
CREATE POLICY "Allow authenticated insert" ON quotes
  FOR INSERT TO authenticated WITH CHECK (true);

-- Allow all users to insert quotes (for public form submission)
DROP POLICY IF EXISTS "Allow anonymous insert" ON quotes;
CREATE POLICY "Allow anonymous insert" ON quotes
  FOR INSERT WITH CHECK (true);

-- Allow admins to manage all quotes
DROP POLICY IF EXISTS "Allow admin full access" ON quotes;
CREATE POLICY "Allow admin full access" ON quotes
  USING (true)
  WITH CHECK (true);
