
-- Drop existing tables and policies to ensure a clean slate
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."pages";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."sections";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."products";
DROP POLICY IF EXISTS "Enable read access for all users" ON "public"."stories";
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."pages";
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."sections";
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."products";
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."stories";
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON "public"."pages";
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON "public"."sections";
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON "public"."products";
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON "public"."stories";
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON "public"."pages";
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON "public"."sections";
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON "public"."products";
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON "public"."stories";

DROP TABLE IF EXISTS "public"."sections";
DROP TABLE IF EXISTS "public"."pages";
DROP TABLE IF EXISTS "public"."products";
DROP TABLE IF EXISTS "public"."stories";

-- Create the pages table
CREATE TABLE "public"."pages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "title" text NOT NULL,
    "slug" text NOT NULL,
    "meta_title" text,
    "meta_description" text,
    "parent_slug" text,
    "nav_order" smallint
);
ALTER TABLE "public"."pages" OWNER TO "postgres";
ALTER TABLE "public"."pages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."pages" ADD CONSTRAINT "pages_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."pages" ADD CONSTRAINT "pages_slug_parent_slug_key" UNIQUE ("slug", "parent_slug");


-- Create the sections table
CREATE TABLE "public"."sections" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "page_id" bigint NOT NULL,
    "type" text NOT NULL,
    "title" text NOT NULL,
    "content" jsonb,
    "visible" boolean NOT NULL DEFAULT true,
    "order" integer NOT NULL,
    "content_structure" jsonb
);
ALTER TABLE "public"."sections" OWNER TO "postgres";
ALTER TABLE "public"."sections" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sections_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."sections" ADD CONSTRAINT "sections_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."sections" ADD CONSTRAINT "sections_page_id_fkey" FOREIGN KEY (page_id) REFERENCES public.pages(id) ON DELETE CASCADE;


-- Create the products table
CREATE TABLE "public"."products" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "short_description" text,
    "long_description" text,
    "main_image" text,
    "features" jsonb,
    "gallery" jsonb,
    "amazon_link" text
);
ALTER TABLE "public"."products" OWNER TO "postgres";
ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."products" ADD CONSTRAINT "products_slug_key" UNIQUE ("slug");

-- Create the stories table
CREATE TABLE "public"."stories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "slug" text NOT NULL,
    "title" text NOT NULL,
    "image" text,
    "dataAiHint" text,
    "category" text,
    "excerpt" text,
    "author" text,
    "authorAvatar" text,
    "date" date,
    "clientImage" text,
    "location" text,
    "project" text,
    "size" text,
    "quote" text,
    "content" text,
    "gallery" jsonb
);
ALTER TABLE "public"."stories" OWNER TO "postgres";
ALTER TABLE "public"."stories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."stories" ADD CONSTRAINT "stories_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."stories" ADD CONSTRAINT "stories_slug_key" UNIQUE ("slug");


-- Insert data into pages
INSERT INTO "public"."pages" (title, slug, meta_title, meta_description, parent_slug, nav_order) VALUES
('Home', 'home', 'Shriram Interio - Pune''s Best Interior Designers', 'Your trusted partner for innovative and elegant interior design solutions in Pune. We specialize in creating personalized spaces that reflect your unique style.', null, 1),
('About', 'about', 'About Shriram Interio | Our Story & Mission', 'Learn about our journey, our design philosophy, and the passionate team dedicated to transforming spaces and lives at Shriram Interio.', null, 2),
('Customer Stories', 'customer-stories', 'Inspiring Customer Stories & Transformations | Shriram Interio', 'Explore our portfolio of success stories and see how we''ve turned our clients'' dreams into reality with stunning interior designs.', null, 3),
('Products', 'products', 'Our Products | Modular Kitchens, Wardrobes & More', 'Discover our wide range of high-quality interior products, including modular kitchens, bespoke wardrobes, and complete home furniture solutions.', null, 4),
('How It Works', 'how-it-works', 'Our Design Process | From Concept to Completion', 'Understand our streamlined and collaborative interior design process that ensures a seamless experience from initial consultation to final handover.', null, 5),
('Services', 'services', 'Our Interior Design Services in Pune | Shriram Interio', 'We offer a comprehensive range of interior design services, from modular kitchens and wardrobes to full home interiors and exterior design.', null, 6),
('Portfolio', 'portfolio', 'Our Portfolio | A Glimpse of Our Best Work', 'Browse through our portfolio to see the quality and creativity of our completed projects, showcasing our expertise in various design styles.', null, 7),
('Contact', 'contact', 'Contact Us | Get in Touch with Shriram Interio', 'Reach out to us for a free consultation or to discuss your project. We''re here to help you create your dream space.', null, 8),
('Clients', 'clients', 'Our Valued Clients & Testimonials | Shriram Interio', 'Hear what our clients have to say about their experience with Shriram Interio. Read their reviews and testimonials.', null, 9),
('Appointment', 'appointment', 'Book an Appointment | Free Design Consultation', 'Schedule a free, no-obligation consultation with our expert interior designers to kickstart your project.', null, 10),
('Get a Quote', 'get-a-quote', 'Get a Free Quote for Your Interior Project | Shriram Interio', 'Request a personalized and detailed quote for your interior design project. It''s free and easy.', null, 11),
('Tracking', 'tracking', 'Track Your Project Status | Shriram Interio', 'Stay updated with the progress of your project in real-time with our easy-to-use project tracking system.', null, 12),
('Login', 'login', 'Login to Your Account | Shriram Interio', 'Access your client dashboard to view project details, documents, and communicate with your design team.', null, 13);


-- Insert data into sections
-- Data for Home page
INSERT INTO "public"."sections" (page_id, type, title, content, "order", content_structure, visible) VALUES
(1, 'hero', 'Hero Section', '{"title": "Transforming Spaces, Inspiring Lives", "subtitle": "Your trusted partner for innovative and elegant interior design solutions in Pune. We specialize in creating personalized spaces that reflect your unique style.", "buttonText": "Explore Our Designs", "videoUrl": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/designer-video.mp4", "slides": [{"image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/hero-1.jpg"}, {"image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/hero-2.jpg"}, {"image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/hero-3.jpg"}]}', 1, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}, "videoUrl": {"type": "text", "label": "Video URL"}, "slides": {"type": "repeater", "label": "Image Slides", "fields": {"image": {"type": "image", "label": "Slide Image"}}}}', true),
(1, 'welcome', 'Welcome Section', '{"paragraph1": "SHRIRAM INTERIO is a place where design meets inspiration and innovation. Founded on the belief that exceptional design transforms lives, we are a team of passionate creatives dedicated to curating spaces that resonate with your soul.", "paragraph2": "Since our establishment in 2016, our journey began with a shared vision: to redefine interior design by infusing creativity, functionality, and a personalized touch into every project. Over the years, we''ve evolved, but our commitment to excellence remains unwavering.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/welcome-image.jpg"}', 2, '{"paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "image": {"type": "image", "label": "Image"}}', true),
(1, 'about_company', 'About Company Section', '{"text": "A vibrant team of designers, engineers, and creative minds who share a common passion for crafting exceptional interiors. With diverse backgrounds and expertise, we bring a unique blend of artistry and technical precision to every project."}', 3, '{"text": {"type": "textarea", "label": "Text"}}', true),
(1, 'why_us', 'Why Us Section', '{"subtitle": "Discover why discerning clients in Pune choose Shriram Interio for their home transformations.", "items": [{"title": "Expert Design Team", "description": "Our team of skilled designers brings creativity and expertise to every project."}, {"title": "Variety of Design Choices", "description": "Choose from a wide range of design options to perfectly match your style."}, {"title": "Affordable Design Fees", "description": "We offer competitive pricing to make your dream home a reality."}, {"title": "On-Time Project Delivery", "description": "We are committed to completing your project on schedule."}]}', 4, '{"subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"title": {"type": "text", "label": "Title"}, "description": {"type": "text", "label": "Description"}}}}', true),
(1, 'work_gallery', 'Work Gallery', '{"subtitle": "Take a look at some of our finest work, showcasing our commitment to quality and creativity.", "items": [{"title": "Modern Living Room", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-1.jpg", "hint": "modern living room"}, {"title": "Elegant Bedroom", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-2.jpg", "hint": "elegant bedroom"}, {"title": "Sleek Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-3.jpg", "hint": "modular kitchen"}]}', 5, '{"subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"title": {"type": "text", "label": "Title"}, "image": {"type": "image", "label": "Image"}, "hint": {"type": "text", "label": "AI Hint"}}}}', true),
(1, 'comfort_design', 'Comfort Design', '{"subtitle": "Experience the future of interior design with our cutting-edge, client-focused services.", "items": [{"title": "Live 3D Designs", "description": "Visualize your space with our interactive 3D modeling services."}, {"title": "Contactless Experience", "description": "From consultation to delivery, enjoy a safe and seamless process."}, {"title": "Instant Pricing", "description": "Get transparent and upfront pricing for your project with no hidden costs."}, {"title": "Expertise & Passion", "description": "Our team is passionate about creating spaces that you''ll love to live in."}]}', 6, '{"subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"title": {"type": "text", "label": "Title"}, "description": {"type": "text", "label": "Description"}}}}', true),
(1, 'what_we_do', 'What We Do', '{"subtitle": "From trendy designs to best-selling classics, we have something for every taste and budget.", "trendingItems": [{"name": "L-Shaped Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-1.jpg", "hint": "l-shaped kitchen"}, {"name": "U-Shaped Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-2.jpg", "hint": "u-shaped kitchen"}, {"name": "Sliding Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-3.jpg", "hint": "sliding wardrobe"}, {"name": "Entertainment Unit", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-4.jpg", "hint": "entertainment unit"}], "bestSellingKitchens": [{"name": "Classic U-Shaped", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-1.jpg", "hint": "classic kitchen"}, {"name": "Modern L-Shaped", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-2.jpg", "hint": "modern kitchen"}, {"name": "Island Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-3.jpg", "hint": "island kitchen"}, {"name": "Parallel Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-4.jpg", "hint": "parallel kitchen"}], "bestSellingWardrobes": [{"name": "Sliding Door", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-1.jpg", "hint": "sliding wardrobe"}, {"name": "Walk-in Closet", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-2.jpg", "hint": "walk-in closet"}, {"name": "Hinged Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-3.jpg", "hint": "hinged wardrobe"}, {"name": "L-Shaped Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-4.jpg", "hint": "l-shaped wardrobe"}]}', 7, '{}', true),
(1, 'testimonials', 'Testimonials', '{"subtitle": "See what our happy clients have to say about their experience with Shriram Interio.", "buttonText": "View All Stories", "items": [{"name": "Rohan & Priya", "review": "The team at Shriram Interio transformed our house into a home. Every detail was perfect!", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-1.jpg"}, {"name": "Anjali Singh", "review": "I couldn''t be happier with my new kitchen. It''s functional, beautiful, and exactly what I wanted.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-2.jpg"}, {"name": "The Sharma Family", "review": "Professional, creative, and delivered on time. We highly recommend Shriram Interio.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-3.jpg"}]}', 8, '{"subtitle": {"type": "text", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}, "items": {"type": "repeater", "label": "Items", "fields": {"name": {"type": "text", "label": "Name"}, "review": {"type": "textarea", "label": "Review"}, "image": {"type": "image", "label": "Image"}}}}', true),
(1, 'faq', 'FAQ', '{"subtitle": "Have questions? We''ve got answers. Here are some of the most common queries we receive.", "items": [{"question": "What is the typical timeline for a project?", "answer": "A typical project can take anywhere from 4 to 8 weeks, depending on the scope and complexity of the design."}, {"question": "Do you offer a warranty?", "answer": "Yes, we offer a comprehensive warranty on all our products and services. Please contact us for more details."}, {"question": "Can I see a 3D model of my design?", "answer": "Absolutely! We provide detailed 3D visualizations to help you see your space before we even begin."}]}', 9, '{"subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"question": {"type": "text", "label": "Question"}, "answer": {"type": "textarea", "label": "Answer"}}}}', true),
(1, 'partners', 'Partners', '{"subtitle": "OUR PARTNERS", "items": [{"name": "Partner 1", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-1.png"}, {"name": "Partner 2", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-2.png"}, {"name": "Partner 3", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-3.png"}, {"name": "Partner 4", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-4.png"}, {"name": "Partner 5", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-5.png"}]}', 10, '{"subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items", "fields": {"name": {"type": "text", "label": "Name"}, "logoSrc": {"type": "image", "label": "Logo"}}}}', true),
-- Data for About page
(2, 'hero', 'Hero Section', '{"title": "Crafting Stories, One Space at a Time", "subtitle": "We believe that every space has a story to tell. Let us help you write yours.", "backgroundImage": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/about-hero.jpg"}', 1, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "backgroundImage": {"type": "image", "label": "Background Image"}}', true),
(2, 'story', 'Our Story', '{"heading": "Our Story", "subheading": "From Humble Beginnings to Pune''s Premier Design Studio", "paragraph1": "Shriram Interio was founded in 2016 with a simple yet powerful mission: to make high-quality interior design accessible to everyone. What started as a small, passionate team has grown into a leading design studio known for its innovation, quality, and commitment to client satisfaction.", "paragraph2": "Our journey has been one of continuous learning and growth. We''ve embraced new technologies, explored diverse design styles, and honed our craft to deliver spaces that are not only beautiful but also functional and timeless.", "paragraph3": "We are more than just designers; we are storytellers. We believe that every home has a unique narrative, and our job is to bring that story to life through thoughtful design and impeccable execution.", "paragraph4": "Our commitment to excellence has earned us a reputation as one of Pune''s most trusted interior design firms. We are proud of the relationships we''ve built with our clients and the beautiful spaces we''ve created together.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/about-story.jpg"}', 2, '{"heading": {"type": "text", "label": "Heading"}, "subheading": {"type": "text", "label": "Subheading"}, "paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "paragraph3": {"type": "textarea", "label": "Paragraph 3"}, "paragraph4": {"type": "textarea", "label": "Paragraph 4"}, "image": {"type": "image", "label": "Image"}}', true),
(2, 'journey', 'Our Journey', '{"heading": "Our Journey", "paragraph1": "The journey of Shriram Interio has been nothing short of inspiring. From our first project to becoming a household name in Pune, our path has been guided by a relentless pursuit of excellence and a deep understanding of our clients'' needs.", "paragraph2": "We started with a focus on modular kitchens and have since expanded our expertise to include full home interiors, wardrobes, and even exterior design. Our growth is a testament to the trust our clients have placed in us and the dedication of our talented team.", "paragraph3": "Each project is a new adventure, a new opportunity to create something extraordinary. We approach every design with fresh eyes, ensuring that each space is a true reflection of its owner''s personality and lifestyle.", "paragraph4": "As we look to the future, we are excited to continue pushing the boundaries of design, exploring new trends, and creating spaces that inspire and delight for years to come.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/about-journey.jpg"}', 3, '{"heading": {"type": "text", "label": "Heading"}, "paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "paragraph3": {"type": "textarea", "label": "Paragraph 3"}, "paragraph4": {"type": "textarea", "label": "Paragraph 4"}, "image": {"type": "image", "label": "Image"}}', true),
(2, 'values', 'Our Values', '{"title": "Our Core Values", "subtitle": "The principles that guide us in everything we do.", "items": [{"title": "Expert Design Team", "description": "Creativity and innovation at the heart of our designs."}, {"title": "Variety of Design Choices", "description": "Unwavering commitment to quality and craftsmanship."}, {"title": "Affordable Design Fees", "description": "Putting our clients at the center of our design process."}, {"title": "On-Time Project Delivery", "description": "Honesty and transparency in all our interactions."}]}', 4, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Value Items", "fields": {"title": {"type": "text", "label": "Value Title"}, "description": {"type": "text", "label": "Description"}}}}', true),
(2, 'mission_vision', 'Mission & Vision', '{"visionTitle": "Our Vision", "visionText": "To be the most sought-after interior design firm in India, renowned for our creativity, quality, and client-centric approach.", "missionTitle": "Our Mission", "missionText": "To transform spaces into beautiful, functional, and personalized environments that enhance the lives of our clients."}', 5, '{"visionTitle": {"type": "text", "label": "Vision Title"}, "visionText": {"type": "textarea", "label": "Vision Text"}, "missionTitle": {"type": "text", "label": "Mission Title"}, "missionText": {"type": "textarea", "label": "Mission Text"}}', true),
(2, 'team', 'Meet the Team', '{"title": "Meet Our Creative Minds", "subtitle": "The passionate and talented individuals behind our success.", "members": [{"name": "Sunita Sharma", "role": "Lead Designer", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/team-1.jpg", "bio": "With over 15 years of experience, Sunita is a master of creating timeless and elegant interiors."}, {"name": "Rajesh Kumar", "role": "Project Manager", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/team-2.jpg", "bio": "Rajesh ensures that every project is executed flawlessly, on time, and within budget."}, {"name": "Priya Singh", "role": "3D Visualizer", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/team-3.jpg", "bio": "Priya brings our designs to life with stunningly realistic 3D visualizations."}]}', 6, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "members": {"type": "repeater", "label": "Team Members", "fields": {"name": {"type": "text", "label": "Name"}, "role": {"type": "text", "label": "Role"}, "image": {"type": "image", "label": "Image"}, "bio": {"type": "textarea", "label": "Bio"}}}}', true),
-- Data for Customer Stories main page
(3, 'header', 'Customer Stories Header', '{"title": "Stories from Happy Homes", "subtitle": "Discover how we''ve helped families across Pune create spaces they love. Each project is a unique journey we''re proud to have been a part of."}', 1, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "textarea", "label": "Subtitle"}}', true),
(3, 'featured_story', 'Featured Story Section', '{"buttonText": "Read Their Story"}', 2, '{"buttonText": {"type": "text", "label": "Button Text"}}', true),
(3, 'more_stories', 'More Stories Section', '{"title": "More Client Stories"}', 3, '{"title": {"type": "text", "label": "Title"}}', true),
-- Data for Products main page (it will dynamically list products)
(4, 'header', 'Products Header', '{"title": "Our Products", "subtitle": "Explore our collection of finely crafted interior solutions."}', 1, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}}', true),
-- Data for How It Works page
(5, 'hero', 'Hero Section', '{"title": "Our Simple 5-Step Process", "subtitle": "From your initial idea to the final handover, we make the journey to your dream home seamless and transparent.", "backgroundImage": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/how-it-works-hero.jpg"}', 1, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "backgroundImage": {"type": "image", "label": "Background Image"}}', true),
(5, 'process', 'Our Process', '{"title": "How It Works", "subtitle": "Our streamlined process ensures a hassle-free experience from start to finish.", "steps": [{"icon": "Handshake", "title": "Consultation", "description": "We start with a detailed consultation to understand your needs, preferences, and budget."}, {"icon": "PencilRuler", "title": "Design & Visualization", "description": "Our team creates a personalized design and 3D model for your approval."}, {"icon": "MessageSquareQuote", "title": "Material Selection & Quote", "description": "We help you choose the best materials and provide a transparent quote."}, {"icon": "Truck", "title": "Execution & Delivery", "description": "Our skilled team brings the design to life with precision and care."}, {"icon": "Star", "title": "Handover & Warranty", "description": "We deliver your dream space and provide a comprehensive warranty."}]}', 2, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "steps": {"type": "repeater", "label": "Steps", "fields": {"icon": {"type": "text", "label": "Icon"}, "title": {"type": "text", "label": "Title"}, "description": {"type": "text", "label": "Description"}}}}', true),
(5, 'why_us', 'Why Our Process Works', '{"title": "Why Our Process Works", "subtitle": "Our client-centric approach is designed to give you peace of mind and exceptional results.", "benefits": [{"icon": "ThumbsUp", "title": "Client-Centric", "description": "Your needs and vision are at the core of everything we do."}, {"icon": "Wallet", "title": "Transparent Pricing", "description": "No hidden costs. We believe in clear and honest communication."}, {"icon": "Smile", "title": "Satisfaction Guaranteed", "description": "We''re not happy until you are. Your satisfaction is our top priority."}]}', 3, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "benefits": {"type": "repeater", "label": "Benefits", "fields": {"icon": {"type": "text", "label": "Icon"}, "title": {"type": "text", "label": "Title"}, "description": {"type": "text", "label": "Description"}}}}', true),
(5, 'get_started', 'Get Started Section', '{"title": "Ready to Start Your Journey?", "subtitle": "Let''s create a space that''s uniquely yours. Schedule a free consultation with our design experts today.", "buttonText": "Book Your Free Consultation"}', 4, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}}', true),
-- Data for Services page
(6, 'header', 'Services Header', '{"title": "Our Services", "subtitle": "Comprehensive design solutions tailored to your needs."}', 1, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}}', true),
(6, 'our_services', 'Our Services', '{"services": [{"title": "Modular Kitchen Design", "description": "Functional and stylish kitchens designed for modern living."}, {"title": "Wardrobe & Storage Solutions", "description": "Customized wardrobes that maximize space and style."}, {"title": "Bedroom Interiors", "description": "Create a serene and personal sanctuary."}, {"title": "Living Area Design", "description": "Spaces designed for comfort, conversation, and connection."}, {"title": "Exterior Design Services", "description": "Enhance your home''s curb appeal with our expert exterior design."}, {"title": "Full Home Interiors", "description": "A complete design overhaul for your entire home."}]}', 2, '{"services": {"type": "repeater", "label": "Services", "fields": {"title": {"type": "text", "label": "Title"}, "description": {"type": "text", "label": "Description"}}}}', true),
(6, 'detailed_services', 'Detailed Services', '{"services": [{"title": "Living Area Design", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/service-living.jpg", "dataAiHint": "modern living area", "href": "/services/living-area-design"}, {"title": "Modular Kitchen", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/service-kitchen.jpg", "dataAiHint": "modular kitchen", "href": "/services/modular-kitchen"}, {"title": "Bedroom", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/service-bedroom.jpg", "dataAiHint": "cozy bedroom", "href": "/services/bedroom"}]}', 3, '{"services": {"type": "repeater", "label": "Services", "fields": {"title": {"type": "text", "label": "Title"}, "imageSrc": {"type": "image", "label": "Image"}, "dataAiHint": {"type": "text", "label": "AI Hint"}, "href": {"type": "text", "label": "Link URL"}}}}', true),
-- Data for Portfolio page
(7, 'projects_gallery', 'Projects Gallery', '{"projects": [{"id": 1, "category": "Kitchen", "title": "Modern Kitchen", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-kitchen-1.jpg", "dataAiHint": "modern kitchen"}, {"id": 2, "category": "Living Room", "title": "Cozy Living Space", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-living-1.jpg", "dataAiHint": "cozy living room"}, {"id": 3, "category": "Bedroom", "title": "Serene Bedroom", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-bedroom-1.jpg", "dataAiHint": "serene bedroom"}]}', 1, '{"projects": {"type": "repeater", "label": "Projects", "fields": {"category": {"type": "text", "label": "Category"}, "title": {"type": "text", "label": "Title"}, "imageSrc": {"type": "image", "label": "Image"}, "dataAiHint": {"type": "text", "label": "AI Hint"}}}}', true),
(7, 'partners', 'Partners', '{"title": "Our Trusted Partners", "subtitle": "In Collaboration With", "items": [{"name": "Partner A", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-1.png"}, {"name": "Partner B", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-2.png"}, {"name": "Partner C", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-3.png"}, {"name": "Partner D", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-4.png"}, {"name": "Partner E", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-5.png"}]}', 2, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Partners", "fields": {"name": {"type": "text", "label": "Name"}, "logoSrc": {"type": "image", "label": "Logo"}}}}', true),
-- Data for Clients page
(9, 'featured_testimonial', 'Featured Testimonial', '{"name": "Amit Patel", "location": "Koregaon Park, Pune", "project": "Full Home Interior", "size": "3 BHK", "quote": "The best interior design decision we ever made. The team was professional, the process was smooth, and the result is beyond our dreams.", "review": "Shriram Interio didn''t just design our house; they gave us a home that truly reflects who we are. Their attention to detail, creativity, and commitment to quality are unparalleled. We couldn''t be happier with the outcome.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-featured.jpg"}', 1, '{"name": {"type": "text", "label": "Name"}, "location": {"type": "text", "label": "Location"}, "project": {"type": "text", "label": "Project"}, "size": {"type": "text", "label": "Size"}, "quote": {"type": "textarea", "label": "Quote"}, "review": {"type": "textarea", "label": "Review"}, "image": {"type": "image", "label": "Image"}}', true),
(9, 'video_testimonials', 'Video Testimonials', '{"title": "Hear From Our Clients", "subtitle": "Watch our clients share their experiences working with Shriram Interio.", "videos": [{"name": "The Gupta Family", "location": "Baner, Pune", "review": "A fantastic experience from start to finish. The 3D designs were a game-changer!", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/video-thumb-1.jpg", "dataAiHint": "happy family", "videoUrl": "#"}, {"name": "Neha Desai", "location": "Viman Nagar, Pune", "review": "My modular kitchen is a dream come true. Functional, beautiful, and delivered on time.", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/video-thumb-2.jpg", "dataAiHint": "woman in kitchen", "videoUrl": "#"}, {"name": "Ravi and Meera", "location": "Hinjewadi, Pune", "review": "The team''s professionalism and creativity exceeded all our expectations.", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/video-thumb-3.jpg", "dataAiHint": "happy couple", "videoUrl": "#"}]}', 2, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "videos": {"type": "repeater", "label": "Videos", "fields": {"name": {"type": "text", "label": "Name"}, "location": {"type": "text", "label": "Location"}, "review": {"type": "text", "label": "Review"}, "imageSrc": {"type": "image", "label": "Thumbnail"}, "dataAiHint": {"type": "text", "label": "AI Hint"}, "videoUrl": {"type": "text", "label": "Video URL"}}}}', true),
(9, 'text_testimonials', 'Text Testimonials', '{"title": "What Our Clients Say", "subtitle": "Read reviews from homeowners who trusted us with their vision.", "testimonials": [{"name": "Rohan Joshi", "review": "Exceptional service and stunning design. Our living room is now our favorite part of the house.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-1.jpg", "avatar": "RJ"}, {"name": "Priya Patil", "review": "The wardrobe design is not only beautiful but incredibly functional. It has transformed my bedroom.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-2.jpg", "avatar": "PP"}, {"name": "Vikram Singh", "review": "A truly professional team that listens to your needs and delivers beyond expectations.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-3.jpg", "avatar": "VS"}]}', 3, '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "testimonials": {"type": "repeater", "label": "Testimonials", "fields": {"name": {"type": "text", "label": "Name"}, "review": {"type": "text", "label": "Review"}, "image": {"type": "image", "label": "Image"}, "avatar": {"type": "text", "label": "Avatar Fallback"}}}}', true);

-- Insert data into products
INSERT INTO "public"."products" (name, slug, short_description, long_description, main_image, features, gallery, amazon_link) VALUES
('Modular Kitchen', 'modular-kitchen', 'High-quality, functional, and stylish modular kitchens.', 'Our modular kitchens are designed to offer a perfect blend of style, functionality, and durability. We use high-quality materials and innovative designs to create kitchens that are not just beautiful but also a joy to work in. From sleek modern designs to classic traditional styles, we have a solution for every home.', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-kitchen.jpg', '["Termite-proof Plywood", "High-gloss Laminate Finish", "Soft-close Drawers", "Customizable Layouts", "LED Task Lighting", "10-Year Warranty"]', '["https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-gallery-1.jpg", "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-gallery-2.jpg"]', 'https://www.amazon.in/'),
('Bedroom Wardrobe', 'bedroom-wardrobe', 'Custom-designed wardrobes for optimal storage and elegance.', 'Maximize your bedroom space with our beautifully crafted wardrobes. We offer a variety of styles, from sliding doors to walk-in closets, all designed to meet your specific storage needs. Our wardrobes are made with premium materials and come in a wide range of finishes to complement your bedroom decor.', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-wardrobe.jpg', '["Custom-fit Design", "Variety of Finishes", "Ample Storage Space", "Durable Hardware", "Integrated Lighting Options", "Space-saving Solutions"]', '["https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-gallery-1.jpg", "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-gallery-2.jpg"]', 'https://www.amazon.in/'),
('Living Room TV Unit', 'living-room-tv-unit', 'Elegant and functional TV units for your living space.', 'Our TV units are designed to be the centerpiece of your living room. They offer a stylish way to organize your entertainment system while providing ample storage for media devices, books, and decor. Choose from a variety of designs, from minimalist floating shelves to elaborate entertainment centers.', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-tv-unit.jpg', '["Sleek, Modern Designs", "Cable Management System", "Multiple Storage Options", "Premium Wood Finishes", "Customizable Dimensions", "Easy Installation"]', '["https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/tv-unit-gallery-1.jpg", "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/tv-unit-gallery-2.jpg"]', 'https://www.amazon.in/');

-- Insert data into stories
INSERT INTO "public"."stories" (slug, title, image, dataAiHint, category, excerpt, author, authorAvatar, date, clientImage, location, project, size, quote, content, gallery) VALUES
('the-patil-residence', 'The Patil Residence: A Modern Marvel in Baner', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-1-main.jpg', 'modern home interior', 'Full Home Interior', 'Discover how we transformed a standard 3BHK flat into a modern, functional, and breathtaking home for the Patil family.', 'Prakash Patil', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-patil.jpg', '2023-11-15', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/client-patil.jpg', 'Baner, Pune', '3 BHK Full Interior', '1200 sq.ft', 'Shriram Interio turned our vision into a reality that exceeded all our expectations.', '<p>The Patil family approached us with a clear vision: a home that was modern, minimalist, yet warm and inviting. Their 3BHK apartment in Baner was a blank canvas, and they trusted us to paint their masterpiece. The challenge was to create a space that was both aesthetically pleasing and highly functional for a family of four.</p><p>Our design philosophy for this project centered around clean lines, a neutral color palette, and the strategic use of natural light. We opted for an open-plan layout for the living and dining areas to create a sense of spaciousness. The kitchen was designed to be the heart of the home, with a sleek, handle-less modular setup and state-of-the-art appliances.</p><p>For the master bedroom, we created a serene retreat with a custom-designed wardrobe that offered ample storage without compromising on style. The children''s room was designed to be playful and vibrant, with flexible furniture that could adapt as they grow. Throughout the home, we used a combination of ambient, task, and accent lighting to create different moods and highlight architectural details. The result is a home that is not just beautiful to look at but a joy to live in.</p>', '[{"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-1-gallery-1.jpg", "alt": "Living Room", "dataAiHint": "modern living room"}, {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-1-gallery-2.jpg", "alt": "Kitchen", "dataAiHint": "modular kitchen"}, {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-1-gallery-3.jpg", "alt": "Bedroom", "dataAiHint": "master bedroom"}]'),
('a-kitchen-renovation-story', 'A Kitchen Renovation Story in Koregaon Park', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-2-main.jpg', 'renovated kitchen', 'Modular Kitchen', 'See how we took an outdated kitchen and turned it into a chef''s paradise with smart design and modern amenities.', 'Anjali Mehta', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-mehta.jpg', '2023-09-22', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/client-mehta.jpg', 'Koregaon Park, Pune', 'Kitchen Renovation', '150 sq.ft', 'My new kitchen is not just a place to cook; it''s the heart of my home now. Thank you, Shriram Interio!', '<p>Anjali, a passionate home chef, felt her kitchen was cramped and outdated. It lacked storage, counter space, and the modern amenities she needed. Her brief was simple: create a kitchen that is both beautiful and hyper-functional.</p><p>We started by completely re-imagining the layout. By removing a non-structural wall, we opened up the space and introduced a breakfast counter, which instantly became a favorite spot for the family. We used a U-shaped layout to maximize counter space and implemented the classic kitchen work triangle for efficiency.</p><p>The material palette was kept light and airy, with high-gloss white laminates and a quartz countertop. We incorporated smart storage solutions like tandem drawers, a magic corner unit, and a tall pantry to declutter the space. The end result was a bright, spacious, and highly efficient kitchen that Anjali loves spending time in.</p>', '[{"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-2-gallery-1.jpg", "alt": "Old kitchen view", "dataAiHint": "old kitchen"}, {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-2-gallery-2.jpg", "alt": "New kitchen layout", "dataAiHint": "new kitchen"}, {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-2-gallery-3.jpg", "alt": "Smart storage solution", "dataAiHint": "kitchen storage"}]');

-- RLS Policies
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."pages"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sections"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."products"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."stories"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

-- Authenticated users can perform all actions
CREATE POLICY "Enable insert for authenticated users only" ON "public"."pages"
FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on user_id" ON "public"."pages"
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for users based on user_id" ON "public"."pages"
FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."sections"
FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on user_id" ON "public"."sections"
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for users based on user_id" ON "public"."sections"
FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."products"
FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on user_id" ON "public"."products"
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for users based on user_id" ON "public"."products"
FOR DELETE TO authenticated USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."stories"
FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for users based on user_id" ON "public"."stories"
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for users based on user_id" ON "public"."stories"
FOR DELETE TO authenticated USING (true);


-- Storage Policies
DROP POLICY IF EXISTS "Enable read access for all users" ON "storage"."objects";
CREATE POLICY "Enable read access for all users" ON "storage"."objects"
AS PERMISSIVE FOR SELECT
TO public
USING (bucket_id = 'public');

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON "storage"."objects";
CREATE POLICY "Enable insert for authenticated users" ON "storage"."objects"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'public');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON "storage"."objects";
CREATE POLICY "Enable update for authenticated users" ON "storage"."objects"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (bucket_id = 'public');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON "storage"."objects";
CREATE POLICY "Enable delete for authenticated users" ON "storage"."objects"
AS PERMISSIVE FOR DELETE
TO authenticated
USING (bucket_id = 'public');
