-- Enable Row Level Security
alter table pages enable row level security;
alter table sections enable row level security;
alter table stories enable row level security;
alter table products enable row level security;

-- Create policies for pages
drop policy if exists "Allow public read access to pages" on pages;
create policy "Allow public read access to pages" on pages for select using (true);

-- Create policies for sections
drop policy if exists "Allow public read access to sections" on sections;
create policy "Allow public read access to sections" on sections for select using (true);

-- Create policies for stories
drop policy if exists "Allow public read access to stories" on stories;
create policy "Allow public read access to stories" on stories for select using (true);

-- Create policies for products
drop policy if exists "Allow public read access to products" on products;
create policy "Allow public read access to products" on products for select using (true);


-- Create storage bucket for public images
insert into storage.buckets (id, name, public)
values ('public', 'public', true)
on conflict (id) do nothing;

-- Create storage bucket policies
drop policy if exists "Allow public read access to public bucket" on storage.objects;
create policy "Allow public read access to public bucket" on storage.objects for select to public using (bucket_id = 'public');

drop policy if exists "Allow authenticated uploads to public bucket" on storage.objects;
create policy "Allow authenticated uploads to public bucket" on storage.objects for insert to authenticated with check (bucket_id = 'public');


-- Create tables
drop table if exists stories cascade;
create table if not exists stories (
  id serial primary key,
  slug text unique not null,
  title text not null,
  image text not null,
  "dataAiHint" text,
  category text not null,
  excerpt text not null,
  author text not null,
  "authorAvatar" text,
  date text not null,
  "clientImage" text,
  location text,
  project text,
  size text,
  quote text,
  content text,
  gallery jsonb
);

drop table if exists products cascade;
create table if not exists products (
    id serial primary key,
    name text not null,
    slug text unique not null,
    short_description text,
    long_description text,
    main_image text,
    features text[],
    gallery text[],
    amazon_link text
);

-- Seed stories table
insert into stories (slug, title, image, "dataAiHint", category, excerpt, author, "authorAvatar", date, "clientImage", location, project, size, quote, content, gallery) values
(
  'modern-kitchen-pune',
  'A Modern Kitchen Transformation in Pune',
  'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-1.jpg',
  'modern kitchen',
  'Kitchens',
  'Discover how we transformed a compact Pune kitchen into a spacious, modern culinary haven with smart storage and elegant finishes.',
  'Priya Sharma',
  'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-1.jpg',
  '2024-05-15',
  'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/client-1.jpg',
  'Koregaon Park, Pune',
  'Full Kitchen Remodel',
  '120 sq. ft.',
  'Shriram Interio turned our dream kitchen into a reality. The team''s professionalism and attention to detail were outstanding!',
  '<p>The Sharma family approached us with a common challenge: a cramped, outdated kitchen that didn''t fit their modern lifestyle. They dreamed of an open, functional space for cooking and family gatherings.</p><p>Our design team started by removing a non-structural wall to open up the layout. We introduced a sleek, U-shaped counter with quartz countertops and installed floor-to-ceiling cabinets in a light grey laminate to maximize storage and reflect light. Smart features like a pull-out pantry, integrated LED lighting, and a magic corner unit were key to optimizing every inch of space.</p><p>The result is a bright, airy, and highly functional kitchen that has become the true heart of their home. The Sharmas were thrilled with the transformation, which not only met but exceeded their expectations.</p>',
  '[
    {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-kitchen-1.jpg", "alt": "Wide angle of the new kitchen", "dataAiHint": "kitchen wide angle"},
    {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-kitchen-2.jpg", "alt": "Close-up of the smart storage solutions", "dataAiHint": "kitchen storage"},
    {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-kitchen-3.jpg", "alt": "The family enjoying their new kitchen", "dataAiHint": "family kitchen"}
  ]'::jsonb
),
(
  'cozy-living-room-makeover',
  'Cozy Living Room Makeover for a Young Couple',
  'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/story-2.jpg',
  'cozy living room',
  'Living Areas',
  'A warm and inviting living space designed for comfort and style, perfect for a young couple''s first home together.',
  'Rahul & Anjali Verma',
  'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-2.jpg',
  '2024-04-20',
  'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/client-2.jpg',
  'Hinjewadi, Pune',
  'Living Room Interior Design',
  '250 sq. ft.',
  'Working with Shriram Interio was a breeze. They understood our vision perfectly and created a space that feels like us.',
  '<p>Rahul and Anjali wanted their first living room to be a sanctuary—a place to unwind after long workdays. Their key requirements were comfort, a neutral color palette, and multi-functional furniture.</p><p>We centered the design around a plush, oversized sofa and a custom-built entertainment unit that concealed all wiring and provided ample storage. A soft, textured rug defined the seating area, while a combination of sheer curtains and blackout blinds offered flexible light control. We incorporated natural elements like a solid wood coffee table and indoor plants to bring warmth and life into the space.</p><p>The final design is a harmonious blend of comfort and contemporary style, creating a perfect backdrop for Rahul and Anjali to build their new life together.</p>',
  '[
    {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-living-1.jpg", "alt": "The comfortable and stylish living room", "dataAiHint": "stylish living room"},
    {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-living-2.jpg", "alt": "Custom entertainment unit detail", "dataAiHint": "entertainment unit"},
    {"src": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-living-3.jpg", "alt": "Cozy reading nook by the window", "dataAiHint": "reading nook"}
  ]'::jsonb
)
on conflict (slug) do update set
  title = excluded.title,
  image = excluded.image,
  "dataAiHint" = excluded."dataAiHint",
  category = excluded.category,
  excerpt = excluded.excerpt,
  author = excluded.author,
  "authorAvatar" = excluded."authorAvatar",
  date = excluded.date,
  "clientImage" = excluded."clientImage",
  location = excluded.location,
  project = excluded.project,
  size = excluded.size,
  quote = excluded.quote,
  content = excluded.content,
  gallery = excluded.gallery;

-- Seed products table
insert into products (name, slug, short_description, long_description, main_image, features, gallery, amazon_link) values
(
    'Modular Kitchens',
    'modular-kitchens',
    'High-quality, custom modular kitchens designed for modern living. Stylish, functional, and built to last.',
    'Discover the heart of your home with a Shriram Interio modular kitchen. We design beautiful, functional spaces that blend elegance and ergonomics, tailored to your unique lifestyle. Our kitchens are built to last, using premium materials and hardware for a seamless cooking experience every day.',
    'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-main.jpg',
    ARRAY['High-quality Plywood & MDF', 'Premium Laminate & Acrylic Finishes', 'German-engineered Hardware', 'Smart Storage Solutions', 'Heat and Scratch Resistant Countertops', 'Customizable Layouts and Colors'],
    ARRAY['https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-1.jpg', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-2.jpg', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-3.jpg'],
    'https://www.amazon.in/'
),
(
    'Custom Wardrobes',
    'custom-wardrobes',
    'Beautifully crafted wardrobes with smart storage solutions. Available in sliding and hinged designs.',
    'Our wardrobes are thoughtfully designed to offer maximum storage while enhancing the aesthetics of your bedroom. From sleek sliding doors to classic hinged designs, we create personalized storage solutions that cater to your specific needs.',
    'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-main.jpg',
    ARRAY['Free-Standing & Built-In Options', 'Smooth Sliding & Hinged Doors', 'Variety of Finishes and Materials', 'Smart Internal Configurations', 'Durable and Termite-Resistant Plywood', 'Integrated Lighting and Mirrors'],
    ARRAY['https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-1.jpg', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-2.jpg', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-3.jpg'],
    'https://www.amazon.in/'
),
(
    'Living Room Furniture',
    'living-room-furniture',
    'Create an inviting living space with our stylish and comfortable sofas, TV units, and coffee tables.',
    'Transform your living room into a hub of comfort and style. Our collection of living room furniture includes everything you need to create a welcoming atmosphere for family and guests, from plush sofas to elegant entertainment centers.',
    'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/living-main.jpg',
    ARRAY['Ergonomic and Comfortable Seating', 'Durable Solid Wood Frames', 'Premium Fabric and Leatherette Options', 'Modular and Customizable Designs', 'Matching Coffee and End Tables'],
    ARRAY['https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/living-1.jpg', 'https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/living-2.jpg'],
    ''
)
on conflict (slug) do update set
  name = excluded.name,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  main_image = excluded.main_image,
  features = excluded.features,
  gallery = excluded.gallery,
  amazon_link = excluded.amazon_link;

-- Seed pages table
insert into pages (title, slug, meta_title, meta_description, parent_slug, nav_order) values
('Home', 'home', 'Shriram Interio | Pune''s Premier Interior Designers', 'Top-rated interior design firm in Pune for modular kitchens, wardrobes, and complete home interiors. Get a free quote today!', null, 1),
('About Us', 'about', 'About Shriram Interio | Our Story & Values', 'Learn about Shriram Interio, our journey since 2016, our design philosophy, and the expert team dedicated to creating your dream home.', null, 2),
('Customer Stories', 'customer-stories', 'Customer Stories & Testimonials | Shriram Interio', 'Read inspiring stories and testimonials from our happy clients. See how we''ve transformed homes across Pune.', null, 3),
('Products', 'products', 'Our Products | Modular Kitchens, Wardrobes & More', 'Explore our wide range of interior products, including custom modular kitchens, bespoke wardrobes, and stylish living room furniture.', null, 4),
('How It Works', 'how-it-works', 'Our Process | From Design to Delivery', 'Understand our simple, transparent 5-step process for interior design, from initial consultation to final handover and warranty.', null, 5),
('Services', 'services', 'Interior Design Services in Pune', 'We offer a complete range of interior design services, including modular kitchens, full home interiors, and commercial space design.', null, 6),
('Portfolio', 'portfolio', 'Our Work | Interior Design Portfolio', 'Browse our portfolio of completed projects. Get inspired by our kitchen, living room, and bedroom designs.', null, 7),
('Contact', 'contact', 'Contact Shriram Interio | Get in Touch', 'Contact us for a free consultation. Visit our office in Pune or get in touch via phone or email.', null, 8),
('Clients', 'clients', 'Our Valued Clients | Testimonials & Reviews', 'See what our clients have to say about their experience with Shriram Interio. Read testimonials and watch video reviews from satisfied homeowners in Pune.', null, 9),
('Appointment', 'appointment', 'Book an Appointment', 'Schedule a free consultation with our design experts.', null, 10),
('Get a Quote', 'get-a-quote', 'Get a Free Quote', 'Request a free, no-obligation quote for your interior design project.', null, 11),
('Tracking', 'tracking', 'Track Your Project', 'Track the status of your ongoing project with Shriram Interio.', null, 12),
('Product: Kitchen', 'kitchen', 'Modular Kitchen Designs', 'Explore our modular kitchen designs.', 'products', 1),
('Product: Wardrobe', 'wardrobe', 'Custom Wardrobe Designs', 'Explore our custom wardrobe designs.', 'products', 2),
('Product: Living Room', 'living-room', 'Living Room Interior Designs', 'Explore our living room interior designs.', 'products', 3),
('Product: Bedroom', 'bedroom', 'Bedroom Interior Designs', 'Explore our bedroom interior designs.', 'products', 4),
('Product: Bathroom', 'bathroom', 'Bathroom Interior Designs', 'Explore our bathroom interior designs.', 'products', 5),
('Product: Home Office', 'home-office', 'Home Office Designs', 'Explore our home office designs.', 'products', 6),
('Product: Space-Saving Furniture', 'space-saving-furniture', 'Space-Saving Furniture Designs', 'Explore our space-saving furniture designs.', 'products', 7)
on conflict (slug) do update set
  title = excluded.title,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  parent_slug = excluded.parent_slug,
  nav_order = excluded.nav_order;


-- Seed sections table
insert into sections (page_id, type, title, content, content_structure, "order", visible) values
((select id from pages where slug = 'home'), 'hero', 'Hero Section', '{"title": "Where Every Corner Tells Your Story", "subtitle": "Pune''s leading interior design company, specializing in modular kitchens, wardrobes, and creating personalized home interiors that reflect your unique style.", "buttonText": "Explore Our Services", "videoUrl": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/hero-video.mp4", "slides": [{"image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/hero-1.jpg"}, {"image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/hero-2.jpg"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "textarea", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}, "videoUrl": {"type": "text", "label": "Background Video URL"}, "slides": {"type": "repeater", "label": "Image Slides"}}', 1, true),
((select id from pages where slug = 'home'), 'welcome', 'Welcome Section', '{"paragraph1": "SHRIRAM INTERIO is a place where design meets inspiration and innovation. Founded on the belief that exceptional design transforms lives, we are a team of passionate creatives dedicated to curating spaces that resonate with your soul.", "paragraph2": "Since our establishment in 2016, our journey began with a shared vision: to redefine interior design by infusing creativity, functionality, and a personalized touch into every project. Over the years, we''ve evolved, but our commitment to excellence remains unwavering.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/welcome-image.jpg"}', '{"paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "image": {"type": "image", "label": "Image"}}', 2, true),
((select id from pages where slug = 'home'), 'about_company', 'About Company Section', '{"title": "About Our Company", "text": "is a premier interior design firm based in Pune, specializing in creating bespoke living spaces since 2016. We believe that a home is more than just a place; it''s a reflection of your personality and a sanctuary for your family. Our team of expert designers works closely with you to bring your vision to life, ensuring every detail is perfect."}', '{"title": {"type": "text", "label": "Title"}, "text": {"type": "textarea", "label": "Text"}}', 3, true),
((select id from pages where slug = 'home'), 'why_us', 'Why Us Section', '{"title": "Why Shriram Interio", "subtitle": "The ultimate destination for all your interior design needs.", "items": [{"title": "Expert Design Team", "description": "Our team''s dedication and passion shine through in every detail."}, {"title": "Variety of Design Choices", "description": "Choose from a wide variety of designs to match your unique style."}, {"title": "Affordable Design Fees", "description": "We offer competitive pricing without compromising on quality."}, {"title": "On-Time Project Delivery", "description": "We guarantee timely completion of all our projects."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 4, true),
((select id from pages where slug = 'home'), 'work_gallery', 'Work Gallery Section', '{"title": "Our Work Gallery", "subtitle": "A Glimpse into Our World of Design", "items": [{"title": "L-Shaped Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-1.jpg", "hint": "modular kitchen"}, {"title": "Elegant Living Room", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-2.jpg", "hint": "living room"}, {"title": "Modern Bedroom Interior", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-3.jpg", "hint": "modern bedroom"}, {"title": "Compact Study Unit", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-4.jpg", "hint": "study unit"}, {"title": "Sliding Door Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-5.jpg", "hint": "sliding wardrobe"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 5, true),
((select id from pages where slug = 'home'), 'comfort_design', 'Comfort Design Section', '{"title": "Design At Your Comfort", "subtitle": "From concept to completion, we handle it all. Our streamlined process ensures a hassle-free experience for you.", "items": [{"title": "Live 3D Designs", "description": "Visualize your space before we even start, with realistic 3D renderings."}, {"title": "Contactless Experience", "description": "Manage your project from anywhere with our seamless digital platform."}, {"title": "Instant Pricing", "description": "Get transparent and upfront pricing for your entire project."}, {"title": "Expertise & Passion", "description": "Our team of seasoned designers brings creativity and dedication to every project."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 6, true),
((select id from pages where slug = 'home'), 'what_we_do', 'What We Do Section', '{"title": "See What We Do", "subtitle": "Explore our trending designs and best-selling products.", "trendingItems": [{"name": "L-Shaped Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-1.jpg", "hint": "modular kitchen"}, {"name": "Sliding Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-2.jpg", "hint": "sliding wardrobe"}, {"name": "Entertainment Unit", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-3.jpg", "hint": "tv unit"}, {"name": "King-size Bed", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/trending-4.jpg", "hint": "king bed"}], "bestSellingKitchens": [{"name": "U-Shaped Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-1.jpg", "hint": "u-shaped kitchen"}, {"name": "Parallel Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-2.jpg", "hint": "parallel kitchen"}, {"name": "Island Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-3.jpg", "hint": "island kitchen"}, {"name": "Straight Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/kitchen-4.png", "hint": "straight kitchen"}], "bestSellingWardrobes": [{"name": "Hinged Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-1.jpg", "hint": "hinged wardrobe"}, {"name": "Sliding Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-2.jpg", "hint": "sliding wardrobe"}, {"name": "Walk-in Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-3.jpg", "hint": "walk-in wardrobe"}, {"name": "Free-standing Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/wardrobe-4.jpg", "hint": "freestanding wardrobe"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "trendingItems": {"type": "repeater", "label": "Trending Items"}, "bestSellingKitchens": {"type": "repeater", "label": "Kitchens"}, "bestSellingWardrobes": {"type": "repeater", "label": "Wardrobes"}}', 7, true),
((select id from pages where slug = 'home'), 'testimonials', 'Testimonials Section', '{"title": "Our Happy Clients", "subtitle": "Don''t just take our word for it. Hear what our satisfied clients have to say.", "buttonText": "View All Testimonials", "items": [{"name": "Sameer Joshi", "review": "Working with Shriram Interio was a pleasure. They transformed our space beautifully and within budget.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-1.jpg"}, {"name": "Anita Desai", "review": "The team''s attention to detail is commendable. Our kitchen is now both functional and gorgeous.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-2.jpg"}, {"name": "Vikram Singh", "review": "Professional, creative, and efficient. Highly recommend their services for anyone looking for quality interiors.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/testimonial-3.jpg"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}, "items": {"type": "repeater", "label": "Items"}}', 8, true),
((select id from pages where slug = 'home'), 'faq', 'FAQ Section', '{"title": "Frequently Asked Questions", "subtitle": "Have questions? We have answers.", "items": [{"question": "What is the typical timeline for a project?", "answer": "A standard 2BHK project typically takes about 45-60 days from design finalization to handover. However, the timeline can vary based on the scope and complexity of the project."}, {"question": "Do you provide a warranty?", "answer": "Yes, we offer a comprehensive 5-year warranty on our modular products and a 1-year warranty on hardware and services."}, {"question": "Can I see my design before implementation?", "answer": "Absolutely! We provide detailed 3D renderings of your space so you can visualize the final outcome and make any changes before we begin execution."}, {"question": "What are the payment terms?", "answer": "Our payment terms are structured in phases: 50% to start the design, 40% before production, and the final 10% upon project completion and handover."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 9, true),
((select id from pages where slug = 'home'), 'partners', 'Partners Section', '{"title": "Our Trusted Partners", "subtitle": "BRANDS WE TRUST", "items": [{"name": "Hettich", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-hettich.png"}, {"name": "Greenply", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-greenply.png"}, {"name": "Asian Paints", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-asianpaints.png"}, {"name": "Saint Gobain", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-saintgobain.png"}, {"name": "Anchor", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-anchor.png"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 10, true),
((select id from pages where slug = 'about'), 'hero', 'Hero Section', '{"title": "About Shriram Interio", "subtitle": "Crafting beautiful and functional spaces since 2016.", "backgroundImage": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/about-hero.jpg"}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "backgroundImage": {"type": "image", "label": "Background Image"}}', 1, true),
((select id from pages where slug = 'about'), 'story', 'Our Story', '{"heading": "Our Story", "subheading": "From a shared vision to a leading design firm.", "paragraph1": "It all started in 2016 with a small team of passionate designers who believed that a well-designed space could significantly enhance one''s quality of life. We wanted to create interiors that were not just aesthetically pleasing but also deeply personal and functional.", "paragraph2": "Our journey began in a modest studio in Pune, where we poured our hearts into every project, no matter how big or small. Our commitment to quality, transparency, and customer satisfaction quickly earned us a reputation for excellence.", "paragraph3": "Word of mouth spread, and our team grew. We expanded our services, embraced new technologies like 3D visualization, and partnered with the best brands in the industry to ensure we delivered nothing but the best to our clients.", "paragraph4": "Today, Shriram Interio is a name synonymous with trust and quality in Pune''s interior design landscape. While we have grown, our core values remain the same: to create beautiful, functional, and timeless spaces that our clients are proud to call home.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/about-story.jpg"}', '{"heading": {"type": "text", "label": "Heading"}, "subheading": {"type": "text", "label": "Subheading"}, "paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "paragraph3": {"type": "textarea", "label": "Paragraph 3"}, "paragraph4": {"type": "textarea", "label": "Paragraph 4"}, "image": {"type": "image", "label": "Image"}}', 2, true),
((select id from pages where slug = 'about'), 'journey', 'Our Journey', '{"heading": "Our Journey", "paragraph1": "Our journey has been one of continuous learning and evolution. We''ve navigated the changing trends of the design world while staying true to our foundational principles of quality and craftsmanship.", "paragraph2": "We invested early in technology, using advanced software to provide live 3D designs that give our clients a clear vision of their future homes. This commitment to innovation has been a cornerstone of our success.", "paragraph3": "Building strong relationships with our partners and suppliers has been key. By working with trusted brands, we ensure that every material and fixture that goes into our projects meets our high standards.", "paragraph4": "Above all, our journey is defined by the stories of the families we''ve worked with. Transforming their houses into homes has been our greatest reward and motivation.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/about-journey.jpg"}', '{"heading": {"type": "text", "label": "Heading"}, "paragraph1": {"type": "textarea", "label": "Paragraph 1"}, "paragraph2": {"type": "textarea", "label": "Paragraph 2"}, "paragraph3": {"type": "textarea", "label": "Paragraph 3"}, "paragraph4": {"type": "textarea", "label": "Paragraph 4"}, "image": {"type": "image", "label": "Image"}}', 3, true),
((select id from pages where slug = 'about'), 'values', 'Our Values', '{"title": "Our Core Values", "subtitle": "The principles that guide everything we do.", "items": [{"title": "Expert Design Team", "description": "Our team''s dedication and passion shine through in every detail."}, {"title": "Variety of Design Choices", "description": "Choose from a wide variety of designs to match your unique style."}, {"title": "Affordable Design Fees", "description": "We offer competitive pricing without compromising on quality."}, {"title": "On-Time Project Delivery", "description": "We guarantee timely completion of all our projects."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 4, true),
((select id from pages where slug = 'about'), 'mission_vision', 'Mission and Vision', '{"visionTitle": "Our Vision", "visionText": "To be Pune''s most trusted and innovative interior design company, transforming spaces into personalized sanctuaries that inspire joy and comfort.", "missionTitle": "Our Mission", "missionText": "To deliver exceptional interior design solutions through a transparent, collaborative, and client-focused process, using the highest quality materials and craftsmanship."}', '{"visionTitle": {"type": "text", "label": "Vision Title"}, "visionText": {"type": "textarea", "label": "Vision Text"}, "missionTitle": {"type": "text", "label": "Mission Title"}, "missionText": {"type": "textarea", "label": "Mission Text"}}', 5, true),
((select id from pages where slug = 'about'), 'team', 'Meet the Team', '{"title": "Meet Our Team", "subtitle": "The creative minds behind your beautiful interiors.", "members": [{"name": "Mr. Shriram", "role": "Founder & Lead Designer", "bio": "With a keen eye for detail and a passion for creating beautiful spaces, Mr. Shriram leads the team with a vision for excellence.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/team-1.jpg"}, {"name": "Priya Singh", "role": "Senior Interior Designer", "bio": "Priya specializes in creating functional and aesthetically pleasing kitchens and living spaces.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/team-2.jpg"}, {"name": "Rajesh Kumar", "role": "Project Manager", "bio": "Rajesh ensures that every project is executed flawlessly and delivered on time, with a focus on quality control.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/team-3.jpg"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "members": {"type": "repeater", "label": "Members"}}', 6, true),
((select id from pages where slug = 'clients'), 'featured_testimonial', 'Featured Testimonial', '{"image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/client-featured.jpg", "name": "The Mehta Family", "location": "Baner, Pune", "project": "Full 3BHK Interior", "size": "1400 sq. ft.", "quote": "From the 3D designs to the final handover, the process was seamless and professional. Our home looks like something out of a magazine!", "review": "We were amazed by the team''s ability to understand our needs and translate them into a design that was both beautiful and practical. Their attention to detail, quality of work, and adherence to timelines were exceptional. We couldn''t be happier with our new home."}', '{"image": {"type": "image", "label": "Client Image"}, "name": {"type": "text", "label": "Client Name"}, "location": {"type": "text", "label": "Location"}, "project": {"type": "text", "label": "Project Type"}, "size": {"type": "text", "label": "Project Size"}, "quote": {"type": "textarea", "label": "Quote"}, "review": {"type": "textarea", "label": "Review"}}', 1, true),
((select id from pages where slug = 'clients'), 'video_testimonials', 'Video Testimonials', '{"title": "Client Video Stories", "subtitle": "Watch our clients share their experiences working with Shriram Interio.", "videos": [{"name": "Rohan & Deepika", "location": "Wakad, Pune", "review": "The kitchen is the heart of our home, and Shriram Interio made it perfect.", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/video-thumb-1.jpg", "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dataAiHint": "couple smiling"}, {"name": "The Joshi Family", "location": "Kothrud, Pune", "review": "Our full home interior was handled with such care and professionalism. Highly recommended.", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/video-thumb-2.jpg", "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dataAiHint": "family portrait"}, {"name": "Alok Verma", "location": "Aundh, Pune", "review": "My wardrobe and bedroom interiors are exactly what I envisioned. Fantastic work!", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/video-thumb-3.jpg", "videoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dataAiHint": "man portrait"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "videos": {"type": "repeater", "label": "Videos"}}', 2, true),
((select id from pages where slug = 'clients'), 'text_testimonials', 'Text Testimonials', '{"title": "What Our Clients Say", "subtitle": "Read reviews from our valued clients.", "testimonials": [{"name": "Prakash Nair", "review": "The quality of materials used is top-notch. Our interiors feel premium and durable. The design team was very patient and incorporated all our feedback.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-3.jpg", "avatar": "PN"}, {"name": "Sunita Kulkarni", "review": "A truly professional team that delivers on their promises. The project was completed on time, and the finishing was impeccable. I''m very happy with their service.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-4.jpg", "avatar": "SK"}, {"name": "Amit Agarwal", "review": "They have a great sense of design and space management. Our small apartment now feels so much more spacious and functional. Excellent work by the entire team.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/avatar-5.jpg", "avatar": "AA"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "testimonials": {"type": "repeater", "label": "Testimonials"}}', 3, true),
((select id from pages where slug = 'customer-stories'), 'header', 'Header Section', '{"title": "Customer Stories", "subtitle": "Discover the real-life stories behind our designs. See how we''ve collaborated with clients to transform their houses into homes they love."}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "textarea", "label": "Subtitle"}}', 1, true),
((select id from pages where slug = 'customer-stories'), 'featured_story', 'Featured Story Section', '{"buttonText": "Read The Full Story"}', '{"buttonText": {"type": "text", "label": "Button Text"}}', 2, true),
((select id from pages where slug = 'customer-stories'), 'more_stories', 'More Stories Section', '{"title": "More Inspiring Stories"}', '{"title": {"type": "text", "label": "Title"}}', 3, true),
((select id from pages where slug = 'customer-stories'), 'work_gallery', 'Work Gallery Section', '{"title": "Our Work Gallery", "subtitle": "A Glimpse into Our World of Design", "items": [{"title": "L-Shaped Modular Kitchen", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-1.jpg", "hint": "modular kitchen"}, {"title": "Elegant Living Room", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-2.jpg", "hint": "living room"}, {"title": "Modern Bedroom Interior", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-3.jpg", "hint": "modern bedroom"}, {"title": "Compact Study Unit", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-4.jpg", "hint": "study unit"}, {"title": "Sliding Door Wardrobe", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/gallery-5.jpg", "hint": "sliding wardrobe"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 4, true),
((select id from pages where slug = 'customer-stories'), 'partners', 'Partners Section', '{"title": "Our Trusted Partners", "subtitle": "BRANDS WE TRUST", "items": [{"name": "Hettich", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-hettich.png"}, {"name": "Greenply", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-greenply.png"}, {"name": "Asian Paints", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-asianpaints.png"}, {"name": "Saint Gobain", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-saintgobain.png"}, {"name": "Anchor", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-anchor.png"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 5, true),
((select id from pages where slug = 'customer-stories'), 'faq', 'FAQ Section', '{"title": "Frequently Asked Questions", "subtitle": "Have questions? We have answers.", "items": [{"question": "What is the typical timeline for a project?", "answer": "A standard 2BHK project typically takes about 45-60 days from design finalization to handover. However, the timeline can vary based on the scope and complexity of the project."}, {"question": "Do you provide a warranty?", "answer": "Yes, we offer a comprehensive 5-year warranty on our modular products and a 1-year warranty on hardware and services."}, {"question": "Can I see my design before implementation?", "answer": "Absolutely! We provide detailed 3D renderings of your space so you can visualize the final outcome and make any changes before we begin execution."}, {"question": "What are the payment terms?", "answer": "Our payment terms are structured in phases: 50% to start the design, 40% before production, and the final 10% upon project completion and handover."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 6, true),
((select id from pages where slug = 'how-it-works'), 'hero', 'Hero Section', '{"title": "Our Process", "subtitle": "A simple, transparent, and collaborative journey to your dream home.", "backgroundImage": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/how-it-works-hero.jpg"}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "backgroundImage": {"type": "image", "label": "Background Image"}}', 1, true),
((select id from pages where slug = 'how-it-works'), 'process', 'Process Section', '{"title": "How It Works", "subtitle": "Your dream home is just 5 simple steps away.", "steps": [{"icon": "Handshake", "title": "1. Consultation & Requirement Gathering", "description": "We start with a detailed discussion to understand your vision, lifestyle, and budget. Our experts will help you refine your ideas."}, {"icon": "PencilRuler", "title": "2. Design & 3D Visualization", "description": "Our designers create a customized plan for your space. You''ll see your home come to life with realistic 3D renderings."}, {"icon": "MessageSquareQuote", "title": "3. Material Selection & Final Quote", "description": "We guide you through selecting the right materials, finishes, and hardware. You receive a final, transparent quote with no hidden costs."}, {"icon": "Truck", "title": "4. Manufacturing & Execution", "description": "Once approved, we begin manufacturing your custom furniture. Our skilled team then handles the installation with precision and care."}, {"icon": "ShieldCheck", "title": "5. Handover & Warranty", "description": "We conduct a final quality check and hand over your beautifully transformed space, complete with our comprehensive warranty."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "steps": {"type": "repeater", "label": "Steps"}}', 2, true),
((select id from pages where slug = 'how-it-works'), 'why_us', 'Why Our Process Works', '{"title": "Why Our Process Works", "subtitle": "We''ve refined our process to be efficient, transparent, and centered around you.", "benefits": [{"icon": "ThumbsUp", "title": "Client-Centric", "description": "Your needs and vision are at the heart of our process. We listen, collaborate, and adapt to ensure you''re delighted with the outcome."}, {"icon": "Wallet", "title": "Transparent Pricing", "description": "No surprises. We provide detailed, itemized quotes so you know exactly where your investment is going."}, {"icon": "Smile", "title": "Hassle-Free Experience", "description": "From design to execution, we manage everything. Sit back and watch your dream home take shape without any of the stress."}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "benefits": {"type": "repeater", "label": "Benefits"}}', 3, true),
((select id from pages where slug = 'how-it-works'), 'get_started', 'Get Started Section', '{"title": "Ready to Start Your Journey?", "subtitle": "Let''s create a space that''s uniquely yours. Schedule a free consultation with our design experts today.", "buttonText": "Book Your Free Consultation"}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "textarea", "label": "Subtitle"}, "buttonText": {"type": "text", "label": "Button Text"}}', 4, true),
((select id from pages where slug = 'services'), 'header', 'Header Section', '{"title": "Our Services", "subtitle": "Comprehensive interior design solutions tailored to your needs."}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}}', 1, true),
((select id from pages where slug = 'services'), 'our_services', 'Our Services List', '{"services": [{"title": "Modular Kitchen Design", "description": "Functional and beautiful kitchens with smart storage solutions."}, {"title": "Wardrobe & Storage Solutions", "description": "Custom wardrobes and storage units to maximize your space."}, {"title": "Bedroom Interiors", "description": "Create a serene and personal sanctuary with our bedroom designs."}, {"title": "Living Area Design", "description": "Stylish and comfortable living spaces for you and your family."}, {"title": "Exterior Design Services", "description": "Enhance your home''s curb appeal with our exterior design expertise."}, {"title": "Full Home Interiors", "description": "A complete, end-to-end solution for your entire home."}]}', '{"services": {"type": "repeater", "label": "Services"}}', 2, true),
((select id from pages where slug = 'services'), 'detailed_services', 'Detailed Services Section', '{"services": [{"title": "Modular Kitchens", "href": "/products/kitchen", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/service-kitchen.jpg", "dataAiHint": "modular kitchen"}, {"title": "Custom Wardrobes", "href": "/products/wardrobe", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/service-wardrobe.jpg", "dataAiHint": "custom wardrobe"}, {"title": "Living Room Design", "href": "/products/living-room", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/service-living.jpg", "dataAiHint": "living room"}]}', '{"services": {"type": "repeater", "label": "Services"}}', 3, true),
((select id from pages where slug = 'portfolio'), 'projects_gallery', 'Projects Gallery', '{"projects": [{"id": 1, "title": "Modern U-Shaped Kitchen", "category": "Kitchens", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-kitchen-1.jpg", "dataAiHint": "u-shaped kitchen"}, {"id": 2, "title": "Minimalist Living Area", "category": "Living Areas", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-living-1.jpg", "dataAiHint": "minimalist living"}, {"id": 3, "title": "Walk-in Wardrobe", "category": "Wardrobes", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-wardrobe-1.jpg", "dataAiHint": "walk-in wardrobe"}, {"id": 4, "title": "Island Kitchen with Breakfast Counter", "category": "Kitchens", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-kitchen-2.jpg", "dataAiHint": "island kitchen"}, {"id": 5, "title": "Cozy Bedroom Retreat", "category": "Bedrooms", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-bedroom-1.jpg", "dataAiHint": "cozy bedroom"}, {"id": 6, "title": "Sliding Door Wardrobe with Mirror", "category": "Wardrobes", "imageSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/portfolio-wardrobe-2.jpg", "dataAiHint": "sliding wardrobe"}]}', '{"projects": {"type": "repeater", "label": "Projects"}}', 1, true),
((select id from pages where slug = 'portfolio'), 'partners', 'Partners Section', '{"title": "Our Trusted Partners", "subtitle": "BRANDS WE TRUST", "items": [{"name": "Hettich", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-hettich.png"}, {"name": "Greenply", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-greenply.png"}, {"name": "Asian Paints", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-asianpaints.png"}, {"name": "Saint Gobain", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-saintgobain.png"}, {"name": "Anchor", "logoSrc": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/logo-anchor.png"}]}', '{"title": {"type": "text", "label": "Title"}, "subtitle": {"type": "text", "label": "Subtitle"}, "items": {"type": "repeater", "label": "Items"}}', 2, true),
((select id from pages where slug = 'kitchen'), 'product_details', 'Product Details', '{"title": "Modular Kitchens", "description": "Discover the heart of your home with a Shriram Interio modular kitchen. We design beautiful, functional spaces that blend elegance and ergonomics, tailored to your unique lifestyle. Our kitchens are built to last, using premium materials and hardware for a seamless cooking experience every day.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-kitchen.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true),
((select id from pages where slug = 'wardrobe'), 'product_details', 'Product Details', '{"title": "Custom Wardrobes", "description": "Our wardrobes are thoughtfully designed to offer maximum storage while enhancing the aesthetics of your bedroom. From sleek sliding doors to classic hinged designs, we create personalized storage solutions that cater to your specific needs.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-wardrobe.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true),
((select id from pages where slug = 'living-room'), 'product_details', 'Product Details', '{"title": "Living Room Interiors", "description": "Create an inviting and comfortable living space for your family and guests. We design everything from TV units and sofas to complete living room layouts.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-living.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true),
((select id from pages where slug = 'bedroom'), 'product_details', 'Product Details', '{"title": "Bedroom Interiors", "description": "Transform your bedroom into a personal sanctuary. We design beautiful and functional bedrooms with custom beds, side tables, and lighting.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-bedroom.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true),
((select id from pages where slug = 'bathroom'), 'product_details', 'Product Details', '{"title": "Bathroom Interiors", "description": "Modern and stylish bathroom designs that maximize space and functionality. We specialize in vanities, storage, and tiling.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-bathroom.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true),
((select id from pages where slug = 'home-office'), 'product_details', 'Product Details', '{"title": "Home Office Interiors", "description": "Create a productive and inspiring workspace at home. We design custom study tables, shelving, and ergonomic office setups.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-office.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true),
((select id from pages where slug = 'space-saving-furniture'), 'product_details', 'Product Details', '{"title": "Space-Saving Furniture", "description": "Maximize your living area with our innovative and multi-functional space-saving furniture, perfect for modern apartments and compact homes.", "image": "https://gzlakbpbhhxxpzbbifus.supabase.co/storage/v1/object/public/public/product-space-saving.jpg"}', '{"title": {"type": "text", "label": "Title"}, "description": {"type": "textarea", "label": "Description"}, "image": {"type": "image", "label": "Image"}}', 1, true)
on conflict (page_id, type) do update set
  title = excluded.title,
  content = excluded.content,
  content_structure = excluded.content_structure,
  "order" = excluded."order",
  visible = excluded.visible;

    